version: "3"
services:
  myapp:
    image: dockware/dev:latest
    container_name: myapp
    volumes:
      - "./:/var/www/html/custom/apps/MyExampleApp"
    ports:
      - "80:80"
      - "3306:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
      - "9998:9998"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=1
networks:
  web:
    external: false
